app_title: Sample App

admin:
  # user id of admin-admin
  login: admin

urls:
  user_dashboard:  /messages

email:
  # Host of the app
  host: bb.noizeramp.com

  # From-field of outgoing mail
  noreply: noreply@trustthevote.org

  # Super-admin email address(es) for notifications
  superadmin: admin@localhost.localdomain

# User account roles
user_roles: [ 'reader', 'writer' ]

# Hook to call after new group saving for further initialization
account_hooks_class_name: AccountHooks
account_after_create_method_name: after_create


# --- DEVELOPMENT

development:

  email:
    host: localhost
    port: 3000
    noreply: noreply@trustthevote.org
    superadmin: admin@localhost.localdomain
