app_title: Sample App

admin:
  # user id of admin-admin
  login: admin

urls:
  user_dashboard:  /user-dashboard

email:
  # From-field of outgoing mail
  noreply: noreply@trustthevote.org

  # Super-admin email address(es) for notifications
  superadmin: admin@localhost.localdomain
