default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: bb
  password: bb
  pool: 5

development:
  <<: *default
  database: bb_de

test:
  <<: *default
  database: bb_t
